require('dotenv').config({ path: '.env.local' });
const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error("Missing Supabase URL or Anon Key");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

const placesData = [
  {
    id: "citadel_hue",
    name: "Đại Nội Huế (Imperial Citadel)",
    category: "heritage",
    description: "Trái tim của cố đô, nơi sinh sống của 13 vị vua triều Nguyễn với kiến trúc cung đình đồ sộ.",
    address: "Đường 23 Tháng 8, Thuận Hòa, Thành phố Huế",
    rating: 4.8,
    rating_count: 5420,
    price: "200,000 VNĐ",
    duration: "2-3 giờ",
    distance: "Trung tâm",
    lat: 16.4687,
    lng: 107.5768,
    img: "https://images.unsplash.com/photo-1590392344717-31fb17d5eec3?auto=format&fit=crop&q=80",
    ai_insight: "Nên đi vào sáng sớm hoặc chiều mát để tránh nắng gắt và có ánh sáng đẹp nhất chụp hình.",
    hours: "07:00 - 17:30",
    hours_time: "Sáng, Chiều",
    hours_note: "Đóng cửa sớm vào mùa đông",
    highlights: JSON.stringify(["Ngọ Môn", "Điện Thái Hòa", "Tử Cấm Thành"]),
    tips: JSON.stringify(["Thuê Audio Guide", "Mang ô/nón", "Mặc trang phục lịch sự"]),
    indoor: 0,
    best_time: "morning",
    crowd_level: "high",
    physical_level: "hard",
    tags: JSON.stringify(["Lịch sử", "Cung đình", "Kiến trúc"]),
    avg_visit_min: 150,
    popularity: 0.95,
    vibe: JSON.stringify(["historic", "grand", "photogenic"]),
    noise_level: "moderate",
    authenticity: 5,
    walking_distance: "extensive",
    accessibility: JSON.stringify(["wheelchair_partial"]),
    weather_dependent: 1,
    best_time_of_day: JSON.stringify(["early_morning", "late_afternoon"]),
    ideal_pacing: "immersive",
    taste_profile: JSON.stringify([]),
    dining_style: null,
    specialties: JSON.stringify([])
  },
  {
    id: "bun_bo_mu_roi",
    name: "Bún Bò Huế Mụ Rơi",
    category: "food",
    description: "Một trong những quán bún bò chuẩn vị Huế lâu đời, nổi tiếng với nước dùng đậm đà và chả cua tự làm cực ngon.",
    address: "40 Nguyễn Chí Diểu, Thuận Thành, Thành phố Huế",
    rating: 4.6,
    rating_count: 850,
    price: "35,000 - 50,000 VNĐ",
    duration: "30-45 phút",
    distance: "Gần Đại Nội",
    lat: 16.4712,
    lng: 107.5821,
    img: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80",
    ai_insight: "Rất gần cửa Hiển Nhơn của Đại Nội, hoàn hảo cho bữa sáng trước khi vào tham quan.",
    hours: "06:00 - 09:30",
    hours_time: "Sáng sớm",
    hours_note: "Thường hết sớm trước 9h",
    highlights: JSON.stringify(["Chả cua", "Nước dùng ruốc", "Thịt bắp bò mềm"]),
    tips: JSON.stringify(["Đến trước 8h sáng", "Ăn kèm ớt sa tế Huế"]),
    indoor: 1,
    best_time: "morning",
    crowd_level: "high",
    physical_level: "easy",
    tags: JSON.stringify(["Local Food", "Ẩm thực", "Bữa sáng"]),
    avg_visit_min: 30,
    popularity: 0.85,
    vibe: JSON.stringify(["local", "bustling", "casual"]),
    noise_level: "loud",
    authenticity: 5,
    walking_distance: "minimal",
    accessibility: JSON.stringify([]),
    weather_dependent: 0,
    best_time_of_day: JSON.stringify(["early_morning"]),
    ideal_pacing: "quick_stop",
    taste_profile: JSON.stringify(["spicy", "savory", "rich"]),
    dining_style: "street_food",
    specialties: JSON.stringify(["bun_bo_hue", "cha_cua"])
  },
  {
    id: "tomb_tu_duc",
    name: "Lăng Tự Đức",
    category: "heritage",
    description: "Một trong những công trình đẹp nhất của kiến trúc cung đình thời Nguyễn, mang đậm chất thơ và sự lãng mạn.",
    address: "Thôn Thượng Ba, Xã Thủy Xuân, Thành phố Huế",
    rating: 4.7,
    rating_count: 3210,
    price: "150,000 VNĐ",
    duration: "1-2 giờ",
    distance: "Cách trung tâm 8km",
    lat: 16.4326,
    lng: 107.5658,
    img: "https://images.unsplash.com/photo-1559592413-7cea4ee01614?auto=format&fit=crop&q=80",
    ai_insight: "Rất rợp bóng cây, phù hợp đi vào buổi trưa hoặc chiều. Gần làng hương Thủy Xuân.",
    hours: "07:00 - 17:30",
    hours_time: "Cả ngày",
    hours_note: "",
    highlights: JSON.stringify(["Hồ Lưu Khiêm", "Xung Khiêm Tạ", "Nhà hát Minh Khiêm"]),
    tips: JSON.stringify(["Kết hợp đi Làng Hương", "Mang thuốc chống muỗi"]),
    indoor: 0,
    best_time: "afternoon",
    crowd_level: "medium",
    physical_level: "moderate",
    tags: JSON.stringify(["Lăng tẩm", "Thơ mộng", "Kiến trúc"]),
    avg_visit_min: 90,
    popularity: 0.9,
    vibe: JSON.stringify(["romantic", "historic", "peaceful"]),
    noise_level: "quiet",
    authenticity: 5,
    walking_distance: "moderate",
    accessibility: JSON.stringify(["wheelchair_partial"]),
    weather_dependent: 1,
    best_time_of_day: JSON.stringify(["afternoon"]),
    ideal_pacing: "immersive",
    taste_profile: JSON.stringify([]),
    dining_style: null,
    specialties: JSON.stringify([])
  },
  {
    id: "cafe_lac",
    name: "Lạc Cafe",
    category: "cafe",
    description: "Quán cafe phong cách bao cấp, nằm ẩn mình trong hẻm nhỏ với không gian cực kỳ chill và yên tĩnh.",
    address: "11 Trương Định, Vĩnh Ninh, Thành phố Huế",
    rating: 4.8,
    rating_count: 450,
    price: "25,000 - 45,000 VNĐ",
    duration: "1-2 giờ",
    distance: "Trung tâm",
    lat: 16.4632,
    lng: 107.5873,
    img: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80",
    ai_insight: "Chỗ trốn hoàn hảo để nghỉ chân sau khi đi bộ nhiều, cà phê muối ở đây rất ngon.",
    hours: "07:00 - 22:00",
    hours_time: "Cả ngày",
    hours_note: "",
    highlights: JSON.stringify(["Cà phê muối", "Không gian retro", "Góc đọc sách"]),
    tips: JSON.stringify(["Thử cà phê muối", "Đi xe máy vì hẻm nhỏ"]),
    indoor: 1,
    best_time: "all",
    crowd_level: "low",
    physical_level: "easy",
    tags: JSON.stringify(["Cafe", "Chill", "Check-in"]),
    avg_visit_min: 90,
    popularity: 0.75,
    vibe: JSON.stringify(["retro", "cozy", "quiet"]),
    noise_level: "quiet",
    authenticity: 4,
    walking_distance: "minimal",
    accessibility: JSON.stringify([]),
    weather_dependent: 0,
    best_time_of_day: JSON.stringify(["morning", "afternoon"]),
    ideal_pacing: "immersive",
    taste_profile: JSON.stringify(["sweet", "salty", "bitter"]),
    dining_style: "cafe",
    specialties: JSON.stringify(["salt_coffee"])
  },
  {
    id: "thien_mu_pagoda",
    name: "Chùa Thiên Mụ",
    category: "heritage",
    description: "Ngôi chùa cổ kính và biểu tượng tâm linh bậc nhất của Huế, nằm bên bờ sông Hương thơ mộng.",
    address: "Đồi Hà Khê, đường Nguyễn Phúc Nguyên, Thành phố Huế",
    rating: 4.8,
    rating_count: 4100,
    price: "Miễn phí",
    duration: "45-60 phút",
    distance: "Cách trung tâm 5km",
    lat: 16.4534,
    lng: 107.5447,
    img: "https://images.unsplash.com/photo-1600868884948-c8402db2fc00?auto=format&fit=crop&q=80",
    ai_insight: "Hoàng hôn nhìn từ chùa Thiên Mụ xuống sông Hương là một trong những cảnh đẹp nhất ở Huế.",
    hours: "08:00 - 18:00",
    hours_time: "Cả ngày",
    hours_note: "",
    highlights: JSON.stringify(["Tháp Phước Duyên", "Đại Hồng Chung", "Sông Hương"]),
    tips: JSON.stringify(["Đi thuyền rồng đến chùa", "Mặc trang phục kín đáo", "Ngắm hoàng hôn"]),
    indoor: 0,
    best_time: "evening",
    crowd_level: "medium",
    physical_level: "easy",
    tags: JSON.stringify(["Tâm linh", "Hoàng hôn", "Miễn phí"]),
    avg_visit_min: 60,
    popularity: 0.95,
    vibe: JSON.stringify(["spiritual", "peaceful", "scenic"]),
    noise_level: "quiet",
    authenticity: 5,
    walking_distance: "minimal",
    accessibility: JSON.stringify([]),
    weather_dependent: 1,
    best_time_of_day: JSON.stringify(["late_afternoon", "sunset"]),
    ideal_pacing: "immersive",
    taste_profile: JSON.stringify([]),
    dining_style: null,
    specialties: JSON.stringify([])
  }
];

async function seedData() {
  console.log("🌱 Bắt đầu bơm dữ liệu vào bảng PLACES...");
  
  const { data, error } = await supabase
    .from('places')
    .upsert(placesData, { onConflict: 'id' });

  if (error) {
    console.error("❌ Lỗi khi seed dữ liệu:", error.message);
  } else {
    console.log(`✅ Đã thêm/cập nhật thành công ${placesData.length} địa điểm!`);
  }
}

seedData();
